### ISSUE TITLE
Joinin signup

### ISSUE THREAD

**Issue by chawyehsu** [pico-8/Joinus#1]
Leave your **GitHub ID** and your comment to the PICO-8 community here if you want to join the organization, we will check it and send the invitation soon, sorry for the slow response.

Happy pico-pico!

**Comment by tobiasvl** [comment]
@2Tie and @MineRobber9000 want in! They're admins at the Discord server and started @pico8dev.

**Comment by chawyehsu** [comment]
Cool, the invitation is sent!

**Comment by ghost** [comment]
@awanisius is my id, can i join?

**Comment by harrison-drift** [comment]
@harry-harrison please!

**Comment by sparr** [comment]
@sparr
Hope I can contribute something! I'm currently starting to curate https://github.com/sparr/pico8lib

**Comment by shitiomatic** [comment]
@shitiomatic

**Comment by lunaisnotaboy** [comment]
@lunaisnotaboy

**Comment by JayantGoel001** [comment]
@JayantGoel001

**Comment by aargar1** [comment]
@aargar1

**Comment by jbampton** [comment]
@jbampton

**Comment by Iardo** [comment]
Hello can I join? @Iardo is my id.
The first letter is an uppercase i, just in case.

**Comment by thuongtruong1009** [comment]
@thuongtruong1009
Nice to meet you, guys!

**Comment by BaseMax** [comment]
Hi everyone.
@BaseMax

**Comment by cixtor** [comment]
Great initiative @chawyehsu . PICO-8 is awesome! @cixtor would like to join the community.

**Comment by phuocantd** [comment]
@phuocantd
Hello world!

**Comment by ericbarrionuevo** [comment]
hi, please invite me to joinin, thank you

**Comment by JhonnyLusonode** [comment]
Hello! Can i get an invite pls? <3
@JhonnyLusonode

**Comment by Sinrez** [comment]
Hi! invite, please. Thank you
https://github.com/Sinrez

**Comment by imbharat420** [comment]
@imbharat420

**Comment by rjbs** [comment]
@rjbs 👈🏽 I'd like to help with doc improvements if possible.

**Comment by Sabyasachi-Seal** [comment]
@Sabyasachi-Seal -> Looking forward to working with y'all

**Comment by thuongtruong109** [comment]
@thuongtruong109

**Comment by kentaurse** [comment]
@kentaurse

**Comment by hi-tech-AI** [comment]
@hi-tech-AI

**Comment by kcraftcode** [comment]
@kentaurse

**Comment by BaseMax** [comment]
@basemax

**Comment by Mehul2711** [comment]
@mehul2711

**Comment by ghzeni** [comment]
@ghzeni

aka [cheddargt](https://www.lexaloffle.com/bbs/?uid=69316)
aka [zeni](https://www.lexaloffle.com/bbs/?pid=161146)

**Comment by gunwixor** [comment]
@gunwixor
hello community!
I want to join

**Comment by thuongtruong109** [comment]
@thuongtruong109

**Comment by anshumanjadiya1102** [comment]
@anshumanjadiya1102 I want to join here

**Comment by HereIsMuhammad** [comment]
@HereIsMuhammad
